---
title: "fastANI_analysis"
author: "Rachel Xu"
date: "10/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(reshape2)
library(plotly)


file_path <- "/Users/rachel/Dropbox/5.Rachel-projects/Phylogeography/Interrogans/"

```

```{r}

fastANI <- read.csv(paste0(file_path,"fastANI_matrix.tsv"),sep="\t") 

fastANI$X440 <- unlist(lapply(fastANI$X440, FUN = function(x){
  unlist(strsplit(unlist(strsplit(x, "/"))[6], "[.]"))[1]
}))
fastANI[is.na(fastANI)] <- NA
# rownames(fastANI) <- fastANI$X440
# remove the last isolate because it does not need to compare with itself
col_names <- c("Sample_Names",fastANI$X440[1:length(fastANI)-1] )
# fastANI <- fastANI %>% select(-c("X440"))
colnames(fastANI) <- col_names
# fastANI <- rbind(col_names, fastANI)
fastANI <- pivot_longer(fastANI,-c("Sample_Names"),names_to = "Sample_Names2",values_to = "ANI", values_drop_na=TRUE)

ani_hm <- ggplot(fastANI,aes(x=Sample_Names, y=Sample_Names2,fill=ANI))+
  geom_tile(color="white") +
   scale_fill_gradient2(low="navy", mid="white", high="red", 
                       midpoint=87, limits=c(75,100))+
   theme(axis.text.x = element_text( vjust = 1, 
    size = 2, angle=90), axis.text.y = element_text(
    size = 2))+
 coord_fixed()

ggplotly(ani_hm)

ggsave(paste0(file_path,"ANI_heatmap.pdf"))

```
