---
title: "Parse_roary_pre/abs"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Pirate to Roary result Analysis
- use workflow from: https://www.lesleysitter.com/2019/08/23/roary-analysis/

```{r}
library(dplyr)
library(reshape2)
library(plyr)
library(plotly)
library(ggfortify)
library(factoextra)
library(tidyverse)


# file_path <- "/Users/rachel/Dropbox/5.Rachel-projects/Phylogeography/Interrogans/"
file_path <- "/Users/rachel/Desktop/workdir/"
```

```{r}
# read in pirate to roary presence/absence csv
file <- as.data.frame(read.csv(paste0(file_path,"pirate_roary_pres_abs.csv")))
head(file)

```

```{r}
info <- within(file,rm("Non.unique.Gene.name","No..isolates","No..sequences","Avg.sequences.per.isolate","Genome.Fragment","Order.within.Fragment","Accessory.Fragment","Accessory.Order.with.Fragment","QC","Min.group.size.nuc","Max.group.size.nuc","Avg.group.size.nuc","Annotation"))

# convert info to matrix
abscence_presence <- as.matrix(info[,-1])
# use annotation as the rownames 
rownames(abscence_presence) <-info[,1]
# if the annotated gene is absent, label 0
abscence_presence[abscence_presence == ""] <- 0
# else present, label 1
abscence_presence[which(abscence_presence!=0)] <- 1


a_p_matrix <- mapply(abscence_presence, FUN=as.numeric)
a_p_matrix <- matrix(data=a_p_matrix, ncol=length(colnames(abscence_presence)), nrow=length(row.names(abscence_presence)))
row.names(a_p_matrix) <- row.names(abscence_presence)
colnames(a_p_matrix) <- colnames(abscence_presence)
# transpose the matrix so observation are rows, attribs are the columns
reversed_ap <- t(a_p_matrix) 

```

```{r}
pdf(paste(file_path,"pres_abs_heatmap.pdf"))
# plot heat map
heatmap_p_a <- heatmap(reversed_ap, col = c("#FFE986","#FF736E"), main = "Absence/Presence of genes", trace="none", labRow=FALSE)
dev.off() 

```

```{r}
# # clean up the metadata files

# 
# 
# # read metadata for all samples
# # this file was produced with python script all_interrogans_metadata.ipynb
# # however, host name, countries were fixed for analysis
# inter_meta<- read.csv(paste0(file_path,"all_interrogans_metadata_440.csv") ) #%>% select(c("BioSample.Accession","Host.Name","Geographic.Location","country","Serovar","Institute","biosample_name"))
# 
# # set empty cell to NA
# inter_meta[inter_meta == ""] <- "NA"
# # fix inconsistency in capitalization
# inter_meta$Serovar <- ifelse(inter_meta$Serovar == "icterohaemorrhagiae", "Icterohaemorrhagiae", inter_meta$Serovar)
# inter_meta$Serovar <- ifelse(inter_meta$Serovar == "pomona", "Pomona", inter_meta$Serovar)
# inter_meta$Serovar <- ifelse(inter_meta$Serovar == "copenhageni", "Copenhageni", inter_meta$Serovar)
# 
# # Seovar name extracted from biosample names
# # some serovar name in biosample name is inconsistent with serovar label
# # Serovar_2 uses serovar in biosample if unmatch
# inter_meta_2 <- inter_meta %>% mutate(Serovar_2=ifelse( grepl("serovar",biosample_name,fixed = TRUE), unlist(lapply(biosample_name,function(x) {unlist(strsplit(x," "))[match("serovar", unlist(strsplit(x," ")))+1]})), Serovar)) 
# 
# # However, if the Serovar weren't labelled specifically, we will use the one defined in the biosample name
# inter_meta_2$Serovar <- ifelse(inter_meta_2$Serovar == "NA", inter_meta_2$Serovar_2, inter_meta_2$Serovar)
# 
# 
# # Serovar fixed
# # write.csv(inter_meta_2,paste0(file_path,"all_interrogans_metadata_440_edited.csv"))



```
### Merge metadata of the isolates with gene presence/absence profile
```{r}
inter_meta_2 <- read.csv("/Users/rachel/Dropbox/5.Rachel-projects/Phylogeography/Interrogans/all_interrogans_metadata_440_edited.csv")

# merge matrix with the metadata
reversed_ap_1 <- as.data.frame(reversed_ap) # reversed_ap were matrix, now to df
write.csv(reversed_ap_1, paste0(file_path,"scoary_trait_pres_abs.csv"), sep=",", quote = FALSE)

reversed_ap_1$BioSample.Accession <- rownames(reversed_ap)
abs_pres_meta <- right_join(inter_meta_2, reversed_ap_1, by="BioSample.Accession")
rownames(abs_pres_meta) <- abs_pres_meta$BioSample.Accession
```
### PCA ANAlYSIS
```{r}


# # complete Pca 
# pca_pa_complete <- prcomp(abs_pres_meta[-c(1:21)])
# pca_plot_complete <- autoplot(pca_pa_complete, data = abs_pres_meta,x=1,y=2)
# ggplotly(pca_plot_complete) 

# remove points with no info for the specific grouping. ex. Seovar, country, Host.Name
pca_matrix <- abs_pres_meta %>% subset(c(serogroups != "NA")) %>% subset( BioSample.Accession != "SAMEA864166")

# write.csv(pca_matrix$BioSample.Accession,paste0(file_path,"sero_avail_isolates.txt",sep="\n"), quote = FALSE, row.names = FALSE, col.names = FALSE)

# pca analysis
pca_pa <- prcomp(pca_matrix[-c(1:25)]) # exclude metadata columns

# get the metadata
metadata <- factor(pca_matrix$serogroups)

# coordinates of each isolates project on to each PC
#head(pca_pa$x) 
unique(metadata)

```
### identify the gene contribute most variation 
```{r}

##### in PC1 ###################

# An eigenvalue is a number, telling you how much variance there is in the data in that direction. The eigenvector with the highest eigenvalue is therefore the principal component
get_eigenvalue(pca_pa)
# find the contribution of each variable to vairation within PC1
PC1_contrib <-sort(get_pca_var(pca_pa)$contrib[,"Dim.1"],decreasing=TRUE)
max(PC1_contrib) #g01317, 0.3673949

# get genes with top contribution to variation
top_contrib_genes <- as.data.frame(PC1_contrib)

# rename variation contribution column
names(top_contrib_genes)[1] <- "PC1_var_contrib"

top_contrib_genes$Gene <- rownames(top_contrib_genes) # prepare for merging

# get gene names and annotation for gene id
gene_names_db <- file %>% select(c("Gene",	"Non.unique.Gene.name",	"Annotation"))
top_contrib_genes$PC1_var_contrib <- as.numeric(top_contrib_genes$PC1_var_contrib)
#typeof(top_contrib_genes$PC1_var_contrib)

# find the name and annotation of genes contribute most to variation
# exclude hypothetical genes
# what are the functions of these genes?
# take t
top_contrib_gene <- left_join(top_contrib_genes, gene_names_db, by ="Gene",all=TRUE) #%>% subset(Annotation != "hypothetical protein") 
write.csv(top_contrib_gene, paste0(file_path,"gene_contrib_PC1.csv"),row.names = FALSE)


##### in PC2 ###################


# find the contribution of each variable to vairation within PC1
PC2_contrib <-sort(get_pca_var(pca_pa)$contrib[,"Dim.2"],decreasing=TRUE)
max(PC2_contrib) #g00158_2, 0.75325491  

# get genes with top contribution to variation
top_contrib_genes2 <- as.data.frame(PC2_contrib)

# rename variation contribution column
names(top_contrib_genes2)[1] <- "PC2_var_contrib"

top_contrib_genes2$Gene <- rownames(top_contrib_genes2) # prepare for merging

# get gene names and annotation for gene id
gene_names_db <- file %>% select(c("Gene",	"Non.unique.Gene.name",	"Annotation"))
top_contrib_genes2$PC2_var_contrib <- as.numeric(top_contrib_genes2$PC2_var_contrib)
# typeof(top_contrib_genes2$PC2_var_contrib)

# find the name and annotation of genes contribute most to variation
# exclude hypothetical genes
# what are the functions of these genes?
top_contrib_gene2 <- left_join(top_contrib_genes2, gene_names_db, by ="Gene",all=TRUE) #%>% subset(Annotation != "hypothetical protein")
write.csv(top_contrib_gene2, paste0(file_path,"gene_contrib_PC2.csv"),row.names = FALSE)
```

### plot PCA
```{r}
# plot pca
# https://cran.r-project.org/web/packages/ggfortify/vignettes/plot_pca.html

fviz_eig(pca_pa) # sree plot
# eigenvalues <1 would mean that the component actually explains less than a single # explanatory variable we discard them

pca_plot <- autoplot(pca_pa, data = pca_matrix, colour = 'serogroups',x=1,y=3)+
  theme_bw()
pca_plot
ggplotly(pca_plot)

# 3d plots
pca_coord <- as.data.frame(pca_pa$x)

plot_ly(pca_coord,x=pca_coord$PC1,y=pca_coord$PC2,z=pca_coord$PC3,color = pca_matrix$serogroups)

pca_matrix$serogroups
```

### organzing serogroups into trait table for SCOARY
```{r}

serogroup_trait <- inter_meta_2 %>% select(c("BioSample.Accession", "serogroups")) %>% subset(serogroups != "NA" & BioSample.Accession != "SAMEA864166") %>% mutate(values= 1) %>% 
  pivot_wider(BioSample.Accession, names_from = serogroups, values_from = values)

serogroup_trait[is.na(serogroup_trait)] <- 0



# write.csv(serogroup_trait, paste0(file_path, "scoary_serogroup_trait.csv"), sep = ",", row.names = FALSE)
```

```{r}
# number of total genomes
genomes_count <- length(colnames(a_p_matrix))
# bind the total number of genes for each genome 
abscence_presence <- cbind(a_p_matrix, rowSums(a_p_matrix))

# create a summary table for each genome
summary_table <- matrix(data=NA, nrow=3, ncol=length(colnames(abscence_presence)))
colnames(summary_table) <- colnames(abscence_presence)
rownames(summary_table) <- c("Total_genes","Unique_genes","Core_genes")

# total genome
summary_table[1,] <- colSums(abscence_presence)
# unique genes (rowsum ==1)
summary_table[2,] <- colSums(abscence_presence[which(abscence_presence[,ncol(abscence_presence)] == 1),])
# 95% core genes
summary_table[3,] <- colSums(abscence_presence[which(abscence_presence[,ncol(abscence_presence)] >= (genomes_count*0.95)),])
summary_table <- summary_table[,-ncol(summary_table)]

```

```{r}
average_table <- data.frame(x=1:6, y=1:6, z=1:6)
# average statistics of all the genomes
average_table[,1] <- c("Total genes analyzed","Orthologous groups","Average gene count","Average core genes","Average unique genes","Total unique genes")
average_table[1,2] <- sum(summary_table[1,])
average_table[2,2] <- length(rownames(abscence_presence))
average_table[3,2] <- median(summary_table[1,])
average_table[4,2] <- length(rownames(abscence_presence[which(abscence_presence[,ncol(abscence_presence)] >= (genomes_count*0.95)),]))
average_table[5,2] <- round(length(rownames(abscence_presence[which(abscence_presence[,ncol(abscence_presence)] == 1),]))/length(colnames(abscence_presence)))
average_table[6,2] <- length(rownames(abscence_presence[which(abscence_presence[,ncol(abscence_presence)] == 1),]))

# reorder the summary table by melting
melt_summary_table <- melt(summary_table)
melt_summary_table <- melt_summary_table[order(melt_summary_table$value),]
```

# Plot Total gene statistics
```{r}

# plot summary table
p1 <- ggplot(melt_summary_table, aes(x = reorder(Var2, value), y = value)) + 
          geom_bar( stat = 'identity') + 
          facet_grid(. ~ Var1, scales = "free_x") + 
          xlab("Genomes") +
          ylab("Count") +
          coord_flip()
p1


# ggsave(paste0(file_path, "all_lepto_genome_stat.pdf"),p1)
```

# plot group by serotypes to observe gene reduction and core gene counts
```{r}

# Plot Number of total genes statistics 
Total_genes <- melt_summary_table %>% subset(c(Var1 == "Total_genes")) %>% select(-c(Var1))
sero_metadata <- inter_meta_2 %>% select(c(BioSample.Accession, Serovar_2, serogroups, Gubbins_BAPS)) %>% subset(serogroups != "NA" & BioSample.Accession != "SAMEA864166") %>% rename(Var2 = BioSample.Accession)

Total_genes <- left_join(sero_metadata, Total_genes)

p2 <- ggplot(Total_genes, aes(x = as.factor(serogroups), y = value)) +
          geom_boxplot() + 
          xlab("Genomes") +
          ylab("Count") +
          coord_flip()
          
p2


# Plot Number of cores genes statistics 
Total_genes <- melt_summary_table %>% subset(c(Var1 == "Core_genes")) %>% select(-c(Var1))
sero_metadata <- inter_meta_2 %>% select(c(BioSample.Accession, Serovar_2, serogroups, Gubbins_BAPS)) %>% subset(serogroups != "NA" & BioSample.Accession != "SAMEA864166") %>% rename(Var2 = BioSample.Accession)

core_genes <- left_join(sero_metadata, Total_genes)

p3 <- ggplot(core_genes, aes(x = as.factor(serogroups), y = value)) +
          geom_boxplot() + 
          xlab("Genomes") +
          ylab("Count") +
          coord_flip()
          
p3

# Plot Number of cores genes statistics 
Total_genes <- melt_summary_table %>% subset(c(Var1 == "Unique_genes")) %>% select(-c(Var1))
sero_metadata <- inter_meta_2 %>% select(c(BioSample.Accession, Serovar_2, serogroups, Gubbins_BAPS)) %>% subset(serogroups != "NA" & BioSample.Accession != "SAMEA864166") %>% rename(Var2 = BioSample.Accession)

unique_genes <- left_join(sero_metadata, Total_genes)

p4 <- ggplot(unique_genes, aes(x = as.factor(Gubbins_BAPS), y = value)) +
          geom_boxplot() + 
          xlab("Genomes") +
          ylab("Count") +
          coord_flip()
          
p4

```