---
title: "treeWAS_VCF_binary"
author: "Rachel Xu"
date: "11/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(dplyr)

file_path <- "/Users/rachel/Desktop/workdir/"
```

# VCF file wrangling 
```{r}

vcf <- read.csv(paste0(file_path, "interrogans_sero.summary_of_snp_distribution.vcf"), sep="\t", header = FALSE)[-c(1:3),c(1:307)] # take out vcf file header
colnames(vcf) <- vcf[1,] # set headers
vcf <- vcf[-1,] 


```

# To binary
```{r}

BioAccession = colnames(vcf)[-c(1:9)]
temp <- data.frame(BioAccession=BioAccession)
rownames(temp) <- BioAccession
for (row in 1:length(vcf[,1])){
  current <- as.data.frame(vcf[row,])
  current_postion <- current$POS
  current_ref <- current$REF
  
  current_column <- as.data.frame(t(as.data.frame(lapply(current[,-c(1:9)],function(x){
    if(x == current_ref){
      return(1)
    }else{
      return(0)
    }
  }))))
colnames(current_column) <- paste0(current_postion, ".",current_ref)
temp <- cbind(temp,current_column)
  current_alt <- unlist(strsplit(current$ALT,","))
  for (alt in 1:length(current_alt)){
    
    current_column <-t(as.data.frame(lapply(current[,-c(1:9)],function(x){
    if(x == current_alt[alt]){
      return(1)
    }else{
      return(0)
    }
  })))
    colnames(current_column) <- paste0(current_postion, ".", current_alt[alt])
    temp <- cbind(temp, current_column)
  }
  
}

temp <- temp %>% select(-c("BioAccession"))
write.csv(paste0(file_path, "snps_binary_sero.csv"))
```


# TreeWAS
```{r}

phen <- as.data.frame(t(read.csv(paste0(file_path,"scoary_serogroup_trait.csv"))))
colnames(phen) <- phen["X",]
phen <- phen[-1,]
tree <- read.tree(paste0(file_path,"int_sero_iqtree.newick"))
treeWAS(temp, phen, tree)

````